return {
  -- {
  --   "MunifTanjim/prettier.nvim",
  --   lazy = false,
  --   opts = function(_, opts)
  --     local prettier = require("prettier")
  --     prettier.setup({
  --       bin = "prettierd", -- or `'prettierd'` (v0.23.3+)
  --       filetypes = {
  --         "css",
  --         "graphql",
  --         "html",
  --         "javascript",
  --         "javascriptreact",
  --         "json",
  --         "less",
  --         "markdown",
  --         "scss",
  --         "typescript",
  --         "typescriptreact",
  --         "yaml",
  --       },
  --     })
  --   end,
  -- },
}
